version: '3'

services:  
  react:
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    volumes:
      - ./front:/home/app/react
    env_file:
      - ./env/local/react.env
    network_mode: host
    stdin_open: true
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    entrypoint: bash
    depends_on:
      - db
    env_file:
      - ./env/local/django.env
    volumes:
      - ./back:/home/app/web
      - dev_static_volume:/home/app/static
      - dev_media_volume:/home/app/media
    ports:
      - "9090:9090"
    stdin_open: true
  db:
    image: "postgres:13.4-alpine"
    build:
      context: .
      dockerfile: ./compose/local/db/Dockerfile
    env_file:
      - ./env/local/db.env
    stdin_open: true
    ports:
      - "9091:5432"
    volumes:
      - dev_postgres_volume:/var/lib/mysql
      - ./db/scripts:/home/app/scripts
  nginx:    
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - 9092:80
    volumes:
      - dev_static_volume:/home/app/static
      - dev_media_volume:/home/app/media
    depends_on:
      - django

volumes:
  dev_postgres_volume:
  dev_static_volume:
  dev_media_volume: