version: "3"

services:
  django_p:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - db_p
    env_file:
      - ./env/production/django.env
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/uploads
  db_p:
    image: "postgres:13.4-alpine"
    env_file:
      - ./env/production/db.env
    volumes:
      - postgres_volume:/var/lib/mysql
  nginx_p:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - 9095:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/uploads
    depends_on:
      - django_p
  react_p:
    build:
      context: .
      dockerfile: ./compose/production/react/Dockerfile
    volumes:
      - ./front:/home/app/react
    env_file:
      - ./env/production/react.env
    ports:
      - 9096:80
    depends_on:
      - nginx_p
volumes:
  postgres_volume:
  static_volume:
  media_volume:
