# Generated by Django 3.2.13 on 2022-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=100, verbose_name='Applicant')),
                ('locationdescription', models.CharField(max_length=150, verbose_name='Description')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('facilitytype', models.CharField(choices=[('Truck', 'Truck'), ('Push Cart', 'Push Cart')], max_length=100, verbose_name='Facility Type')),
                ('objectid', models.IntegerField(null=True, verbose_name='Objectid')),
                ('schedule', models.TextField(verbose_name='Link Schedule')),
            ],
            options={
                'verbose_name': 'FoodTruck',
                'verbose_name_plural': 'FoodTrucks',
            },
        ),
    ]
